### ISSUE TITLE
前端大爆炸! - WEB BANG! BANG!! BANG!!! 

### ISSUE THREAD

**Issue by Fantasy9527** [Fantasy9527/alili.tech#1]

**Comment by JAEFORIGHT** [comment]
大哥 我还有一个问题就是我想在about的页面里写一个可以跳转到其他页面的链接 就按照你的_resume的格式来写的 但是就是找不到界面 有空的时候可以帮看一下吗 改了一个晚上都没改过来 
![image](https://user-images.githubusercontent.com/44728260/54072531-d5cd6680-42b6-11e9-95a4-d4018604dd16.png)

然后我那个博客执行完hugo项目地址是https://github.com/JAEFORIGHT/blog
