### ISSUE TITLE
typed.js的那个打字机的内容设置了也无法实现每天更新

### ISSUE THREAD

**Issue by JAEFORIGHT** [Fantasy9527/alili.tech#3]
有空的时候能贴一下总共要改哪些地方的配置吗，总觉得我是有点细节没弄好，但是又没找出哪错了，求博主大大有空解答一下·_·

**Comment by Fantasy9527** [comment]
哦,是这样的,我有爬虫服务每天更新仓库内容的.

**Comment by JAEFORIGHT** [comment]
懂了 谢谢 我去看看

**Comment by JAEFORIGHT** [comment]
对了还有就是爬下来的内容我也不知道设置到哪里，感觉就是找不到

**Comment by JAEFORIGHT** [comment]
在shanbeiToday里 我之前找的有点太急了 问的问题可能有点太傻了 我会努力提高自己提问的智慧的 对不起了

**Comment by Fantasy9527** [comment]
@JAEFORIGHT  世上没有傻问题
